// Generated by CoffeeScript 1.10.0
var rec;

rec = new Path.Rectangle(new Point(40, 40), new Size(40, 40));

rec.strokeColor = 'black';

rec.fillColor = new Color(0, 255, 0);

Path.RegularPolygon();
