// Generated by CoffeeScript 1.10.0
var gridSize, raster, spacing;

raster = new Raster('logo');

raster.visible = false;

gridSize = 12;

spacing = 2.2;

raster.on('load', function() {
  var color, path, x, y;
  raster.size = new Size(80, 60);
  y = 0;
  while (y < raster.height) {
    x = 0;
    while (x < raster.width) {
      color = raster.getPixel(x, y);
      path = new Path.Circle({
        center: new Point(x, y) * gridSize,
        radius: gridSize / 2 / spacing
      });
      path.fillColor = color;
      x++;
    }
    y++;
  }
  project.activeLayer.position = view.center;
});

project.activeLayer.position = view.center;
