# Create a raster item using the image tag with id='mona'
raster = new Raster('logo')
# Hide the raster:
raster.visible = false
# The size of our grid cells:
gridSize = 12
# Space the cells by 120%:
spacing = 2.2
# As the web is asynchronous, we need to wait for the raster to load
# before we can perform any operation on its pixels.
raster.on 'load', ->
# Since the example image we're using is much too large,
# and therefore has way too many pixels, lets downsize it to
# 40 pixels wide and 30 pixels high:
	raster.size = new Size(80, 60)
	y = 0
	while y < raster.height
		x = 0
		while x < raster.width
# Get the color of the pixel:
			color = raster.getPixel(x, y)
			# Create a circle shaped path:
			path = new (Path.Circle)(
				center: new Point(x, y) * gridSize
				radius: gridSize / 2 / spacing)
			# Set the fill color of the path to the color
			# of the pixel:
			path.fillColor = color
			x++
		y++
	# Move the active layer to the center of the view, so all
	# the created paths in it appear centered.
	project.activeLayer.position = view.center
	return
# Move the active layer to the center of the view:
project.activeLayer.position = view.center

# ---
# generated by js2coffee 2.2.0