onFrame = (event)->
	count = event.count
	paper.project.activeLayer.removeChildren();
	paper.view.draw();
	x = 0


	while x < 15
		y = 0
		while y < 15
			xsin = Math.sin(x)
			ysin = Math.sin(y)
			rec = new (Path.Rectangle)(new Point(x * 40, y * 40), new Size(40, 40))
			rec.strokeColor = 'black'
			rec.fillColor = new Color(0, x / 10, y / 10)
			rec.strokeWidth = 2
			rec.scale ysin+xsin + Math.sin(count / 10)
			rec.rotate  ysin*100*Math.sin(count / 10)
			y++
		x++

# ---
# generated by js2coffee 2.2.0